name: Echo

on:
  push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Dummy echo with some more text"
  echo2:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo
        run: echo "second job"
